version: '2'
services:
  modeling-app:
    image: activiti/activiti-cloud-modeling-backend:7-201802-EA
    external_links:
      - activiti-cloud-sso-idm
      - activiti-cloud-registry
      - rabbitmq
    environment:
      - ACT_MODELING_PORT=8088
      - ACT_MODELING_HOST=modeling-app
      - ACT_MODELING_APP_NAME=modeling-app
      - ACT_CLOUD_CONFIG_SERVER_ENABLED=false
